name:                manki
version:             0.1.0.0
github:              reinasta/manki
license:             BSD3
author:              Andrei Nasta
maintainer:          reinasta@gmail.com
copyright:           2020 Andrei Nasta

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/manki#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- megaparsec >= 7.0.0
- containers >= 0.6.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  manki:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - manki
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  manki:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - manki
    - hspec
    - hspec-megaparsec >= 2.0.0

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
