name:                manki
version:             0.1.0.0
github:              reinasta/manki
license:             BSD3
author:              Andrei Nasta
maintainer:          reinasta@gmail.com
copyright:           2025 Andrei Nasta

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/manki#readme>

dependencies:
- base >= 4.19 && < 4.20
- rio >= 0.1.22.0
- megaparsec >= 9.6.1
- containers >= 0.6.8
- random >= 1.2.1
- QuickCheck >= 2.14.3
- aeson >= 2.2.3.0
- text >= 2.1.1
- hspec >= 2.11.12
- hspec-core
- optparse-applicative
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - hspec-core

executables:
  manki-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - manki
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  manki:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - manki
    - hspec
    - hspec-megaparsec >= 2.2.1

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
